#
# Copyright 2023-2024 Appmattus Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[versions]

java = "11"
kotlin = "1.9.10"

androidGradlePlugin = "8.1.2"
detektGradlePlugin = "1.23.1"
dokkaPlugin = "1.9.0"
gradleMavenPublishPlugin = "0.25.3"
gradleVersionsPlugin = "0.36.0"
markdownlintGradlePlugin = "0.6.0"
owaspDependencyCheckPlugin = "8.4.0"

coroutines = "1.7.3"
highlightJs = "1.5.0"
okhttp = "4.12.0"
okio = "3.6.0"
retrofit = "2.9.0"
volley = "1.2.1"
orbit = "6.1.0"

jacoco = "0.8.10"
bouncyCastle = "1.76"
equalsVerifier = "3.15.2"
junit4 = "4.13.2"
mockito = "5.5.0"
mockitoKotlin = "5.1.0"
robolectric = "4.10.3"
classgraph = "4.8.162"

desugar = "1.1.5"

androidX-appCompat = "1.6.1"
androidX-lifecycle = "2.6.2"
androidX-compose-ui = "1.5.3"
androidX-compose-foundation = "1.4.3"
androidX-compose-material = "1.5.3"
androidX-compose-compiler = "1.5.3"
androidX-activityCompose = "1.8.0"
androidX-lifecycleViewmodelCompose = "2.6.1"
androidX-navigationCompose = "2.7.4"

androidX-testCore = "1.5.0"
androidX-testExtJunit = "1.1.5"
androidX-testRunner = "1.5.2"

google-material = "1.9.0"
google-playServices = "18.2.0"

kotlinX-serialization = "1.6.0"


[plugins]

detektGradlePlugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektGradlePlugin" }
dokkaPlugin = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
gradleMavenPublishPlugin = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublishPlugin" }
gradleVersionsPlugin = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
markdownlintGradlePlugin = { id = "com.appmattus.markdown", version.ref = "markdownlintGradlePlugin" }
owaspDependencyCheckPlugin = { id = "org.owasp.dependencycheck", version.ref = "owaspDependencyCheckPlugin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-pluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
